"""ai-cockpit loss functions and mission scores.

Generated by loss-forge for the ai-cockpit project.
Pure computation — no side effects, no writes, read-only checks.

Usage:
    cockpit grade          # human-readable instrument panel
    cockpit grade --json   # machine-readable for tracking
"""

import hashlib
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# ─── Constants ───────────────────────────────────────────

EXPECTED_COMMANDS = [
    "new", "can-i-close", "touch-and-go", "scan", "status",
    "list", "config", "marketplace", "doctor", "version",
    "upgrade", "add", "remove", "help",
]

EXPECTED_SKILLS = [
    "takeoff", "land", "touch-and-go", "can-i-close",
    "cockpit-status", "cockpit-repair", "pre-flight", "clean-sweep",
]

LIFECYCLE_COMMANDS = ["new", "can-i-close", "touch-and-go"]


def _project_root():
    """Find the ai-cockpit-template project root."""
    # Walk up from this file to find pyproject.toml
    p = Path(__file__).parent
    for _ in range(5):
        if (p / "pyproject.toml").exists():
            return p
        p = p.parent
    return Path(__file__).parent.parent.parent


def _run(cmd, timeout=10):
    """Run a command, return stdout or None."""
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return r.stdout.strip() if r.returncode == 0 else None
    except Exception:
        return None


def _file_sha(path):
    """SHA256 of a file's contents."""
    try:
        return hashlib.sha256(Path(path).read_bytes()).hexdigest()
    except Exception:
        return None


# ─── Missions (higher is better, max 1.0) ────────────────


def m1_zero_to_flying():
    """M1: Can a new user go from pip install to working cockpit?"""
    root = _project_root()
    checks = {
        "pyproject_exists": (root / "pyproject.toml").exists(),
        "entry_point_defined": False,
        "template_bundled": (root / "src" / "ai_cockpit" / "template" / "CLAUDE.md").exists(),
        "template_has_skills": (root / "src" / "ai_cockpit" / "template" / ".claude" / "skills" / "takeoff" / "skill.md").exists(),
        "template_has_state": (root / "src" / "ai_cockpit" / "template" / "state.json").exists(),
        "readme_has_install": False,
        "readme_has_quickstart": False,
    }

    # Check entry point
    try:
        toml_text = (root / "pyproject.toml").read_text()
        checks["entry_point_defined"] = "cockpit = " in toml_text
    except Exception:
        pass

    # Check README
    try:
        readme = (root / "README.md").read_text()
        checks["readme_has_install"] = "pip install ai-cockpit" in readme
        checks["readme_has_quickstart"] = "cockpit new" in readme
    except Exception:
        pass

    passed = sum(1 for v in checks.values() if v)
    return {
        "score": passed / len(checks),
        "weight": 10,
        "components": checks,
    }


def m2_fleet_awareness():
    """M2: Can the user see state of all cockpits at a glance?"""
    checks = {
        "list_command": "list" in EXPECTED_COMMANDS,
        "status_command": "status" in EXPECTED_COMMANDS,
        "cic_fleet_wide": True,  # can-i-close runs across all cockpits
        "tag_fleet_wide": True,  # touch-and-go runs across all cockpits
        "tui_exists": False,
    }

    # Check TUI code exists
    root = _project_root()
    try:
        cli_text = (root / "src" / "ai_cockpit" / "cli.py").read_text()
        checks["tui_exists"] = "class CockpitApp" in cli_text
    except Exception:
        pass

    passed = sum(1 for v in checks.values() if v)
    return {"score": passed / len(checks), "weight": 8, "components": checks}


def m3_safe_close():
    """M3: Does the system prevent work loss on close?"""
    root = _project_root()
    checks = {
        "cic_skill_exists": (root / ".claude" / "skills" / "can-i-close" / "skill.md").exists(),
        "cic_cli_exists": False,
        "land_gated": False,
        "tag_skill_exists": (root / ".claude" / "skills" / "touch-and-go" / "skill.md").exists(),
        "tag_cli_exists": False,
    }

    try:
        cli_text = (root / "src" / "ai_cockpit" / "cli.py").read_text()
        checks["cic_cli_exists"] = "cmd_can_i_close" in cli_text
        checks["tag_cli_exists"] = "cmd_touch_and_go" in cli_text
        checks["land_gated"] = "can-i-close" in (root / ".claude" / "skills" / "land" / "skill.md").read_text()
    except Exception:
        pass

    passed = sum(1 for v in checks.values() if v)
    return {"score": passed / len(checks), "weight": 9, "components": checks}


def m4_lifecycle_completeness():
    """M4: Are all 4 lifecycle primitives functional?"""
    root = _project_root()
    primitives = {
        "takeoff_skill": (root / ".claude" / "skills" / "takeoff" / "skill.md").exists(),
        "tag_skill": (root / ".claude" / "skills" / "touch-and-go" / "skill.md").exists(),
        "tag_cli": False,
        "cic_skill": (root / ".claude" / "skills" / "can-i-close" / "skill.md").exists(),
        "cic_cli": False,
        "land_skill": (root / ".claude" / "skills" / "land" / "skill.md").exists(),
    }

    try:
        cli_text = (root / "src" / "ai_cockpit" / "cli.py").read_text()
        primitives["tag_cli"] = "cmd_touch_and_go" in cli_text
        primitives["cic_cli"] = "cmd_can_i_close" in cli_text
    except Exception:
        pass

    passed = sum(1 for v in primitives.values() if v)
    return {"score": passed / len(primitives), "weight": 7, "components": primitives}


def m5_plugin_discovery():
    """M5: Can users find and install Claude Code plugins?"""
    root = _project_root()
    checks = {
        "marketplace_command": False,
        "marketplace_in_readme": False,
        "marketplace_in_new": False,
    }

    try:
        cli_text = (root / "src" / "ai_cockpit" / "cli.py").read_text()
        checks["marketplace_command"] = "cmd_marketplace" in cli_text
        checks["marketplace_in_new"] = "cockpit marketplace" in cli_text
    except Exception:
        pass

    try:
        readme = (root / "README.md").read_text()
        checks["marketplace_in_readme"] = "eidos-marketplace" in readme
    except Exception:
        pass

    passed = sum(1 for v in checks.values() if v)
    return {"score": passed / len(checks), "weight": 5, "components": checks}


def m6_self_documenting():
    """M6: Does every command have help and every feature have docs?"""
    root = _project_root()
    try:
        cli_text = (root / "src" / "ai_cockpit" / "cli.py").read_text()
    except Exception:
        return {"score": 0.0, "weight": 6, "components": {}}

    checks = {}
    for cmd in EXPECTED_COMMANDS:
        # Check if --help is handled (look for help text patterns)
        checks[f"{cmd}_in_help"] = cmd in cli_text

    # Check README has CLI table
    try:
        readme = (root / "README.md").read_text()
        checks["readme_cli_table"] = "CLI Commands" in readme
        checks["changelog_current"] = "v0.2.0" in (root / "CHANGELOG.md").read_text()
        checks["contributing_exists"] = (root / "CONTRIBUTING.md").exists()
    except Exception:
        pass

    passed = sum(1 for v in checks.values() if v)
    return {"score": passed / len(checks) if checks else 0.0, "weight": 6, "components": checks}


# ─── Losses (lower is better, 0.0 = perfect) ────────────


def l1_untested_commands():
    """L1: CLI commands without test coverage."""
    root = _project_root()
    test_dir = root / "tests"
    if not test_dir.exists():
        return {"value": len(EXPECTED_COMMANDS), "weight": 8, "components": {"tested": [], "untested": EXPECTED_COMMANDS}}

    try:
        test_text = ""
        for f in test_dir.glob("*.py"):
            test_text += f.read_text()
    except Exception:
        return {"value": len(EXPECTED_COMMANDS), "weight": 8, "components": {}}

    tested = []
    untested = []
    for cmd in EXPECTED_COMMANDS:
        # Look for test references to command
        if cmd.replace("-", "_") in test_text or cmd in test_text:
            tested.append(cmd)
        else:
            untested.append(cmd)

    return {
        "value": len(untested),
        "weight": 8,
        "components": {"tested": tested, "untested": untested},
    }


def l2_template_drift():
    """L2: Bundled template skills out of sync with repo skills."""
    root = _project_root()
    repo_skills = root / ".claude" / "skills"
    bundled_skills = root / "src" / "ai_cockpit" / "template" / ".claude" / "skills"

    if not repo_skills.exists() or not bundled_skills.exists():
        return {"value": 1.0, "weight": 7, "components": {"error": "dirs missing"}}

    drifted = []
    synced = []
    for skill_dir in sorted(repo_skills.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_file = skill_dir / "skill.md"
        bundled_file = bundled_skills / skill_dir.name / "skill.md"

        if not skill_file.exists():
            continue

        repo_sha = _file_sha(skill_file)
        bundled_sha = _file_sha(bundled_file)

        if repo_sha == bundled_sha:
            synced.append(skill_dir.name)
        else:
            drifted.append(skill_dir.name)

    total = len(synced) + len(drifted)
    return {
        "value": len(drifted) / total if total else 0.0,
        "weight": 7,
        "components": {"synced": synced, "drifted": drifted},
    }


def l3_hardcoded_paths():
    """L3: Absolute paths that aren't config-based."""
    root = _project_root()
    cli_file = root / "src" / "ai_cockpit" / "cli.py"
    if not cli_file.exists():
        return {"value": 1.0, "weight": 6, "components": {}}

    text = cli_file.read_text()
    import re
    # Look for hardcoded home directory paths (not in comments/strings about examples)
    pattern = r'Path\.home\(\)\s*/\s*"repos-'
    matches = re.findall(pattern, text)

    return {
        "value": len(matches),
        "weight": 6,
        "components": {"hardcoded_path_count": len(matches), "pattern": pattern},
    }


def l4_missing_help():
    """L4: Commands that don't handle --help properly."""
    root = _project_root()
    cli_module = root / "src" / "ai_cockpit" / "cli.py"

    # Commands that should have --help handling
    commands_needing_help = ["can-i-close", "touch-and-go", "new", "config"]

    try:
        text = cli_module.read_text()
    except Exception:
        return {"value": len(commands_needing_help), "weight": 5, "components": {}}

    missing = []
    covered = []
    for cmd in commands_needing_help:
        fn_name = f"cmd_{cmd.replace('-', '_')}"
        # Find the function and check if it handles --help
        if f'"--help" in args' in text or f'"--help"' in text:
            covered.append(cmd)
        else:
            missing.append(cmd)

    # More precise: check each function individually
    missing = []
    covered = []
    for cmd in commands_needing_help:
        fn_name = f"cmd_{cmd.replace('-', '_')}"
        # Find function body and look for --help
        idx = text.find(f"def {fn_name}")
        if idx == -1:
            missing.append(cmd)
            continue
        # Look in next 500 chars for --help handling
        snippet = text[idx:idx + 500]
        if "--help" in snippet:
            covered.append(cmd)
        else:
            missing.append(cmd)

    return {
        "value": len(missing),
        "weight": 5,
        "components": {"covered": covered, "missing": missing},
    }


def l5_stale_pypi():
    """L5: Git version doesn't match published PyPI version."""
    from ai_cockpit import __version__ as local_version

    try:
        r = subprocess.run(
            [sys.executable, "-m", "pip", "index", "versions", "ai-cockpit"],
            capture_output=True, text=True, timeout=10,
        )
        if r.returncode == 0 and "Available versions:" in r.stdout:
            # Parse latest version
            versions_line = [l for l in r.stdout.splitlines() if "Available versions:" in l]
            if versions_line:
                latest = versions_line[0].split(":")[1].strip().split(",")[0].strip()
                match = local_version == latest
                return {
                    "value": 0.0 if match else 1.0,
                    "weight": 4,
                    "components": {"local": local_version, "pypi": latest, "match": match},
                }
    except Exception:
        pass

    return {
        "value": 0.0,  # Can't check = assume ok
        "weight": 4,
        "components": {"local": local_version, "pypi": "unknown", "match": "unknown"},
    }


def l6_code_mass():
    """L6: cli.py size — should stabilize, not grow unbounded."""
    root = _project_root()
    cli_file = root / "src" / "ai_cockpit" / "cli.py"

    try:
        lines = len(cli_file.read_text().splitlines())
    except Exception:
        return {"value": 1.0, "weight": 3, "components": {}}

    # Threshold: 1500 lines is healthy, 2000+ is a smell
    threshold = 1500
    excess = max(0, lines - threshold) / threshold

    return {
        "value": round(excess, 2),
        "weight": 3,
        "components": {"lines": lines, "threshold": threshold},
    }


# ─── Composites ──────────────────────────────────────────


def compute_all():
    """Compute all missions and losses. Returns the full scorecard."""
    missions = {
        "M1_zero_to_flying": m1_zero_to_flying(),
        "M2_fleet_awareness": m2_fleet_awareness(),
        "M3_safe_close": m3_safe_close(),
        "M4_lifecycle_completeness": m4_lifecycle_completeness(),
        "M5_plugin_discovery": m5_plugin_discovery(),
        "M6_self_documenting": m6_self_documenting(),
    }

    losses = {
        "L1_untested_commands": l1_untested_commands(),
        "L2_template_drift": l2_template_drift(),
        "L3_hardcoded_paths": l3_hardcoded_paths(),
        "L4_missing_help": l4_missing_help(),
        "L5_stale_pypi": l5_stale_pypi(),
        "L6_code_mass": l6_code_mass(),
    }

    # Weighted mission composite
    m_total_weight = sum(m["weight"] for m in missions.values())
    mission_composite = sum(m["score"] * m["weight"] for m in missions.values()) / m_total_weight

    # Weighted loss composite
    l_total_weight = sum(l["weight"] for l in losses.values())
    loss_composite = sum(l["value"] * l["weight"] for l in losses.values()) / l_total_weight

    return {
        "loss_composite": round(loss_composite, 2),
        "mission_composite": round(mission_composite, 2),
        "missions": missions,
        "losses": losses,
        "snapshot_date": datetime.now().strftime("%Y-%m-%d"),
    }


def print_panel():
    """Print human-readable instrument panel."""
    data = compute_all()

    print()
    print("  " + "=" * 56)
    print(f"    AI-COCKPIT INSTRUMENT PANEL  |  {data['snapshot_date']}")
    print("  " + "=" * 56)
    print(f"    LOSS: {data['loss_composite']:.2f}  (lower is better)")
    print(f"    MISSION: {data['mission_composite']:.2f}  (higher is better, max 1.0)")
    print("  " + "=" * 56)
    print()

    # Mission bars
    for name, m in data["missions"].items():
        pct = int(m["score"] * 100)
        bar_filled = int(m["score"] * 20)
        bar = "\033[32m" + "█" * bar_filled + "\033[90m" + "░" * (20 - bar_filled) + "\033[0m"
        label = name.ljust(28)
        weight = f"(w:{m['weight']})"
        print(f"    {bar} {pct:3d}%  {label} {weight}")

    print()

    # Loss details
    print("    \033[1mLOSSES\033[0m")
    for name, l_data in data["losses"].items():
        val = l_data["value"]
        if val == 0:
            indicator = "\033[32m✓\033[0m"
        elif val < 1:
            indicator = "\033[33m!\033[0m"
        else:
            indicator = "\033[31m✗\033[0m"
        label = name.ljust(28)
        detail = ""
        comps = l_data.get("components", {})
        if "untested" in comps and comps["untested"]:
            detail = f"untested: {', '.join(comps['untested'][:3])}"
        elif "drifted" in comps and comps["drifted"]:
            detail = f"drifted: {', '.join(comps['drifted'][:3])}"
        elif "lines" in comps:
            detail = f"{comps['lines']} lines"
        elif "missing" in comps and comps["missing"]:
            detail = f"missing: {', '.join(comps['missing'])}"
        elif "match" in comps:
            detail = f"local={comps.get('local')} pypi={comps.get('pypi')}"

        print(f"    {indicator} {val:5.2f}  {label} {detail}")

    print()
